<?php
if (!defined('_PS_VERSION_')) {
    exit;
}

class Myparcel extends Module
{
    protected $config_form = false;
    const LOG_TABLE = 'myparcel_log';

    public function __construct()
    {
        $this->name = 'myparcel';
        $this->tab = 'shipping_logistics';
        $this->version = '1.0.0';
        $this->author = 'Generated by ChatGPT';
        $this->need_instance = 0;
        $this->ps_versions_compliancy = array('min' => '1.7.0.0', 'max' => '1.7.99.99');
        $this->bootstrap = true;
        parent::__construct();
        $this->displayName = $this->l('MyParcel - Post integration (MVP)');
        $this->description = $this->l('Send orders to external postal API when order state changes, save tracking, and generate printable labels (MVP).');
    }

    public function install()
    {
        if (!parent::install() ||
            !$this->registerHook('actionOrderHistoryAddAfter')
        ) {
            return false;
        }
        return $this->installDb();
    }

    public function uninstall()
    {
        return $this->uninstallDb() && parent::uninstall();
    }

    protected function installDb()
    {
        $sql = "CREATE TABLE IF NOT EXISTS `"._DB_PREFIX_.self::LOG_TABLE."` (
            `id_log` INT AUTO_INCREMENT PRIMARY KEY,
            `id_shop` INT NOT NULL,
            `id_order` INT NOT NULL,
            `order_reference` VARCHAR(64),
            `status` ENUM('pending','sent','error','done') DEFAULT 'pending',
            `payload` TEXT,
            `response` TEXT,
            `tracking_number` VARCHAR(128),
            `attempts` INT DEFAULT 0,
            `last_attempt` DATETIME NULL,
            INDEX (id_order),
            INDEX (id_shop)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;";
        return Db::getInstance()->execute($sql);
    }

    protected function uninstallDb()
    {
        return Db::getInstance()->execute("DROP TABLE IF EXISTS `"._DB_PREFIX_.self::LOG_TABLE."`");
    }

    public function getContent()
    {
        $output = '';
        if (Tools::isSubmit('submitMyparcelModule')) {
            $api_url = Tools::getValue('MYPARCEL_API_URL');
            $api_key = Tools::getValue('MYPARCEL_API_KEY');
            $states = Tools::getValue('MYPARCEL_TARGET_STATES');
            Configuration::updateValue('MYPARCEL_API_URL', $api_url, false, null, $this->context->shop->id);
            Configuration::updateValue('MYPARCEL_API_KEY', $api_key, false, null, $this->context->shop->id);
            Configuration::updateValue('MYPARCEL_TARGET_STATES', json_encode(array_map('intval', (array)$states)), false, null, $this->context->shop->id);
            $output .= $this->displayConfirmation($this->l('Settings updated'));
        }

        // Handle retry action
        if (Tools::isSubmit('retry_log') && ($id_log = (int)Tools::getValue('id_log'))) {
            $this->retryLog($id_log);
            $output .= $this->displayConfirmation($this->l('Retry initiated.'));
        }

        $output .= $this->renderForm();
        $output .= $this->renderLogs();
        return $output;
    }

    protected function renderForm()
    {
        $api_url = Configuration::get('MYPARCEL_API_URL', null, null, $this->context->shop->id);
        $api_key = Configuration::get('MYPARCEL_API_KEY', null, null, $this->context->shop->id);
        $target_states = json_decode(Configuration::get('MYPARCEL_TARGET_STATES', null, null, $this->context->shop->id) ?: '[]', true);

        $html = '<form method="post" class="defaultForm form-horizontal">
        <fieldset>
        <legend>'.$this->l('API Settings').'</legend>
        <div class="form-group">
            <label class="control-label col-lg-3">'.$this->l('API URL').'</label>
            <div class="col-lg-9"><input name="MYPARCEL_API_URL" type="text" class="form-control" value="'.htmlspecialchars($api_url).'"></div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-3">'.$this->l('API Key (Bearer)').'</label>
            <div class="col-lg-9"><input name="MYPARCEL_API_KEY" type="text" class="form-control" value="'.htmlspecialchars($api_key).'"></div>
        </div>
        <div class="form-group">
            <label class="control-label col-lg-3">'.$this->l('Target order states (IDs, comma separated)').'</label>
            <div class="col-lg-9"><input name="MYPARCEL_TARGET_STATES" type="text" class="form-control" value="'.htmlspecialchars(implode(',', $target_states)).'"></div>
            <p class="help-block">'.$this->l('When an order changes to one of these state IDs, the module will send the order to API. Example: 5,10').'</p>
        </div>
        <div class="form-group"><div class="col-lg-offset-3 col-lg-9"><button class="btn btn-default" name="submitMyparcelModule" type="submit">'.$this->l('Save').'</button></div></div>
        </fieldset></form><hr/>';

        return $html;
    }

    protected function renderLogs()
    {
        $sql = 'SELECT * FROM `'._DB_PREFIX_.self::LOG_TABLE.'` ORDER BY id_log DESC LIMIT 200';
        $rows = Db::getInstance()->executeS($sql);
        $html = '<h3>'.$this->l('Recent logs').'</h3>';
        $html .= '<table class="table"><thead><tr><th>ID</th><th>Shop</th><th>Order</th><th>Status</th><th>Tracking</th><th>Attempts</th><th>Last attempt</th><th>Actions</th></tr></thead><tbody>';
        foreach ($rows as $r) {
            $html .= '<tr>';
            $html .= '<td>'.$r['id_log'].'</td>';
            $html .= '<td>'.$r['id_shop'].'</td>';
            $html .= '<td>'.$r['order_reference'].' ('.$r['id_order'].')</td>';
            $html .= '<td>'.$r['status'].'</td>';
            $html .= '<td>'.htmlspecialchars($r['tracking_number']).'</td>';
            $html .= '<td>'.$r['attempts'].'</td>';
            $html .= '<td>'.$r['last_attempt'].'</td>';
            $html .= '<td>
                <form method="post" style="display:inline">
                    <input type="hidden" name="id_log" value="'.$r['id_log'].'"/>
                    <button type="submit" name="retry_log" class="btn btn-default btn-sm">'.$this->l('Retry').'</button>
                </form>
                <a class="btn btn-default btn-sm" href="'.htmlspecialchars($this->context->link->getAdminLink('AdminModules').'&configure='.$this->name.'&view_label='.$r['id_order']).'">'.$this->l('View label').'</a>
            </td>';
            $html .= '</tr>';
        }
        $html .= '</tbody></table>';
        // show label if requested
        if (Tools::getValue('view_label') && ($id_order = (int)Tools::getValue('view_label'))) {
            $label_path = $this->getLabelPath($id_order);
            if (file_exists($label_path)) {
                $content = Tools::file_get_contents($label_path);
                $html .= '<h4>'.$this->l('Label for order').' '.$id_order.'</h4>';
                $html .= '<div style="border:1px solid #ddd;padding:10px;">'. $content .'</div>';
            } else {
                $html .= '<div class="alert alert-warning">'.$this->l('Label not found for order').' '.$id_order.'</div>';
            }
        }
        return $html;
    }

    public function hookActionOrderHistoryAddAfter($params)
    {
        if (!isset($params['order_history'])) return;
        $orderHistory = $params['order_history'];
        $newOrderStateId = (int)$orderHistory->id_order_state;
        $targetStates = json_decode(Configuration::get('MYPARCEL_TARGET_STATES', null, null, $this->context->shop->id) ?: '[]', true);
        if (!is_array($targetStates) || !in_array($newOrderStateId, $targetStates)) {
            return;
        }
        $id_order = (int)$orderHistory->id_order;
        $order = new Order($id_order);
        $payload = $this->buildPayloadFromOrder($order);

        Db::getInstance()->insert(self::LOG_TABLE, [
            'id_shop' => (int)$this->context->shop->id,
            'id_order' => $id_order,
            'order_reference' => pSQL($order->reference),
            'payload' => pSQL(json_encode($payload)),
            'status' => 'pending',
            'attempts' => 0,
            'last_attempt' => null
        ]);

        // Synchronous attempt
        $this->processSendOrder($id_order, $payload);
    }

    protected function buildPayloadFromOrder($order)
    {
        $address = new Address($order->id_address_delivery);
        $customer = new Customer($order->id_customer);
        $items = [];
        foreach ($order->getProducts() as $p) {
            $items[] = [
                'name' => $p['product_name'],
                'sku' => $p['product_reference'],
                'qty' => (int)$p['product_quantity'],
                'weight' => isset($p['product_weight']) ? $p['product_weight'] : 0
            ];
        }
        $payload = [
            'order_id' => $order->id,
            'reference' => $order->reference,
            'shop_id' => $this->context->shop->id,
            'customer' => [
                'firstname' => $customer->firstname,
                'lastname' => $customer->lastname,
                'phone' => $address->phone ?: $customer->phone_mobile ?: $customer->phone,
                'email' => $customer->email,
            ],
            'address' => [
                'address1' => $address->address1,
                'address2' => $address->address2,
                'city' => $address->city,
                'postcode' => $address->postcode,
                'country' => $address->country
            ],
            'items' => $items,
            'total_paid' => $order->total_paid
        ];
        return $payload;
    }

    protected function processSendOrder($id_order, $payload)
    {
        $apiUrl = Configuration::get('MYPARCEL_API_URL', null, null, $this->context->shop->id);
        $apiKey = Configuration::get('MYPARCEL_API_KEY', null, null, $this->context->shop->id);
        if (!$apiUrl) return false;

        $ch = curl_init($apiUrl);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_POST, true);
        $headers = ['Content-Type: application/json'];
        if ($apiKey) $headers[] = 'Authorization: Bearer '.$apiKey;
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
        curl_setopt($ch, CURLOPT_TIMEOUT, 30);
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        $err = curl_error($ch);
        curl_close($ch);

        $log = Db::getInstance()->getRow('SELECT * FROM `'._DB_PREFIX_.self::LOG_TABLE.'` WHERE id_order='.(int)$id_order.' ORDER BY id_log DESC LIMIT 1');
        $id_log = $log['id_log'] ?? 0;

        if ($httpCode >= 200 && $httpCode < 300 && $response) {
            $resp = json_decode($response, true);
            $tracking = $resp['tracking'] ?? $resp['tracking_number'] ?? $resp['data']['tracking'] ?? null;
            if ($tracking) {
                // Update order_carrier tracking
                $orderCarrierId = $order = new Order($id_order);
                $orderCarrier = $order->getIdOrderCarrier();
                if ($orderCarrier) {
                    $oc = new OrderCarrier($orderCarrier);
                    $oc->tracking_number = pSQL($tracking);
                    $oc->save();
                }
                Db::getInstance()->update(self::LOG_TABLE, [
                    'response' => pSQL($response),
                    'tracking_number' => pSQL($tracking),
                    'status' => 'done',
                    'attempts' => (int)$log['attempts'] + 1,
                    'last_attempt' => pSQL(date('Y-m-d H:i:s'))
                ], 'id_log='.(int)$id_log);

                // generate simple label html
                $this->generateLabelHtml($id_order, $payload, $tracking);

                // try to send SMS (placeholder)
                $this->sendSmsToCustomer($order->id_customer, $tracking, $payload['reference'] ?? '');
                return true;
            }
        }

        Db::getInstance()->update(self::LOG_TABLE, [
            'response' => pSQL($response ?: $err),
            'status' => 'error',
            'attempts' => (int)$log['attempts'] + 1,
            'last_attempt' => pSQL(date('Y-m-d H:i:s'))
        ], 'id_log='.(int)$id_log);

        return false;
    }

    protected function generateLabelHtml($id_order, $payload, $tracking)
    {
        $dir = dirname(__FILE__).'/labels';
        if (!is_dir($dir)) @mkdir($dir, 0755, true);
        $html = '<div style="font-family:Arial,Helvetica,sans-serif;padding:10px;border:1px solid #000;width:350px;">';
        $html .= '<h3>Label - Order '.$payload['reference'].'</h3>';
        $html .= '<p><strong>Tracking:</strong> '.$tracking.'</p>';
        $html .= '<p><strong>Name:</strong> '.htmlspecialchars($payload['customer']['firstname'].' '.$payload['customer']['lastname']).'</p>';
        $html .= '<p><strong>Phone:</strong> '.htmlspecialchars($payload['customer']['phone']).'</p>';
        $html .= '<p><strong>Address:</strong> '.htmlspecialchars($payload['address']['address1'].' '.$payload['address']['address2'].', '.$payload['address']['city'].' '.$payload['address']['postcode']).'</p>';
        $html .= '<hr/>';
        $html .= '<p style="font-size:12px;">Please use your browser print to print this label.</p>';
        $html .= '</div>';
        file_put_contents($dir."/label_{$id_order}.html", $html);
    }

    protected function getLabelPath($id_order)
    {
        return dirname(__FILE__).'/labels/label_'.$id_order.'.html';
    }

    protected function sendSmsToCustomer($id_customer, $tracking, $order_ref)
    {
        // Placeholder: module has a hook point to integrate SMS provider.
        $cust = new Customer($id_customer);
        $mobile = $cust->phone_mobile ?: $cust->phone;
        if (!$mobile) return false;
        // Admin can replace this with real provider details. For now we store a log entry.
        Db::getInstance()->insert(self::LOG_TABLE, [
            'id_shop' => (int)$this->context->shop->id,
            'id_order' => 0,
            'order_reference' => pSQL('SMS:'.$mobile),
            'payload' => pSQL(json_encode(['message' => "Tracking $tracking for order $order_ref"])),
            'response' => pSQL('sms-placeholder'),
            'status' => 'sent',
            'attempts' => 0,
            'last_attempt' => pSQL(date('Y-m-d H:i:s'))
        ]);
        return true;
    }

    protected function retryLog($id_log)
    {
        $row = Db::getInstance()->getRow('SELECT * FROM `'._DB_PREFIX_.self::LOG_TABLE.'` WHERE id_log='.(int)$id_log);
        if (!$row) return false;
        $payload = json_decode($row['payload'], true);
        if (!$payload) return false;
        return $this->processSendOrder($row['id_order'], $payload);
    }
}
